import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TISC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img
          className={styles.myimg}
          src="/tisclogo.png"
          alt="IITJ Logo"
          width={300}
        />
        <h1 className={styles.title}>Innovation Pipeline for TISC</h1>
        <p className={styles.description}>
          Technology Innovation and Startup Centre (TISC) is set up at IIT
          Jodhpur to provide incubation space for startups and innovators. This
          setup aims at nucleating a cluster of new age ventures around the
          focal theme of “Artificial Intelligence of Things (AIOT)” which is
          thematically unique in the country.
        </p>

        <p className=" font-bold hover:text-color-">
          <Link href={"http://tisc.iitj.ac.in/"}>Learn More...</Link>
        </p>
        {/* <Link href={`${process.env.NEXT_PUBLIC_HOST}/login`}>
          <button
            type="submit"
            className="inline-block px-7 py-3 bg-slate-900 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-slate-700 hover:shadow-lg focus:bg-slate-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out w-full"
            data-mdb-ripple="true"
            data-mdb-ripple-color="light"
          >
            Login
          </button>
        </Link> */}
      </main>
    </div>
  );
}
